#!/bin/bash

###########################################################################
# This is a script to display colums of the fract_bonds files in the current 
# directory
###########################################################################

# Christophe.martin@grenoble-inp.fr    November 2006
BINARY_std=$(whereis -b cdp3D | awk '{print $NF}' | rev | sed 's/D3pdc//' | rev)
theuser=`whoami`

file2display=fract_bonds_running



Option_l="$2 $3 $4 $5 $6 $7 $8 $9 $10 $11 $12 $13 $14 $15 $16"
keepfile=$(echo $Option_l | grep -c "\-keep")
crack2compute=$(echo $Option_l | grep -c "\-crack_length")


# need to compute the crack_length as post_processing of fract_bonds:
if [ $crack2compute != "0" ] ;then
   last_coord=$(ls -1 _coord[0-9][0-9][0-9][0-9] | tail -1)
   cdp3D -crack_length $last_coord 
fi
# if dp3D is running cdp3D -craack_length will create filefract_bonds_running instead of fract_bonds:
if [ -f fract_bonds_running ];then
  file2display=fract_bonds_running
else
  file2display=fract_bonds
fi

# need a $file2display file in the current directory
# need a file2display file in the current directory
if [ -f $file2display ];then     
  echo ""
  numcol=`head -1 $file2display | awk '{print NF }'`
  let "numcol = numcol + 1"
else
  echo '!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!'       
  echo "file $file2display does not exist !"
  echo '!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!'       	 
  exit
fi     
# the list of xaxis columns that are missing in this file:
listxmissing="-dgeom -timestep -time_s -time_h -Temp"
# addmissingXcolumn pastes the column missing into the visco$file2display and returns isdollar1missing 0 or 1
source $BINARY_std/addmissingXcolumn


case $1 in
  -dens )
      Xlabel='"Relative Density "'
      correct_fact=$(grep correct_fact.*=[0-9] input_dp3D | head -1 | cut -c 17-)
      if [ "$correct_fact" = "" ];then
        correct_fact=1.
        Xcolumn='($1)'
      else
        Xcolumn='($1/'$correct_fact')' 
        echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
        echo "Using correction factor from input_dp3D for density  "
        echo "correc_fact="$correct_fact 
        echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
      fi
      ;;
  -dgeom )
      Xlabel='"Geometric Relative Density "'
      Xcolumn='($'$numcol')'
      ;;
  -epsx )
      Xlabel='"Strain (x)"'
      Xcolumn='($2)'
      ;; 
  -epsy )
      Xlabel='"Strain (y)"'
      Xcolumn='($3)'
      ;; 
  -epsz )
      Xlabel='"Strain (z)"'
      Xcolumn='($4)'
      ;; 
  -timestep )
      Xlabel='"Timestep "'
      Xcolumn='($'$numcol')'
      ;;
  -time_s )
      Xlabel='"Time (sec) "'
      Xcolumn='($'$numcol')'
      ;;
  -time_h )
      Xlabel='"Time (hour) "'
      Xcolumn='($'$numcol')'
      ;;
  -Temp )
      Xlabel='"Temperature (deg. C) "'
      Xcolumn='($'$numcol')'
      ;;
     * )
       echo " $1 is not a valid x label"
       echo " valid x labels are  -dens -dgeom : density / geometric density"
       echo "                     -epsx -epsy -epsz : x y and z strain"
       echo ""
       echo " valid y labels are  -elastic_en   : Stored elastic energy"
       echo "                     -crack_length : crack_length"
      exit 
esac
# gnup_display  is the standard view for gnuplot and display_  
cp -f "$BINARY_std"gnup_display plot_$file2display

    echo "set xlabel $Xlabel" >> plot_$file2display
    let "i=0"
    end_option="$1"0

    for option in $Option_l
    do
    case $option in
    -elastic_en )
      Title='"Elastic_energy"'
      Ylabel='"E (mJ)"'
      Ycolumn='($14)'
       ;;
    -crack_length  )
      Title='"crack_length "'
      Ylabel='"length (microns)"'
      Ycolumn='($19)'
       ;;       
     xrange* )
      range_string=$(echo $option | sed 's/xrange/set xrange /' | sed 's/\//\[/' | sed 's/\//\]/')
      sed -i "s|#set xrange|$range_string|1" plot_$file2display 
      plot="no"
      ;;
     yrange* )
      range_string=$(echo $option | sed 's/yrange/set yrange /' | sed 's/\//\[/' | sed 's/\//\]/')
      sed -i "s|#set yrange|$range_string|1" plot_$file2display 
      plot="no"
      ;;
    anim )
      export file2display Xcolumn Ycolumn
      $BINARY_std/animate_my_gif 
      plot="no"
      ;;
     * )
      if [ "$option" = "$end_option" -a $i -gt 0 -o "$option" = "-keep"  ];then
# this is the end of the y label list, no more to plot
 	if [ $keepfile = "0" ];then
	  gnuplot -geometry 560x400 -persist plot_$file2display 
# finally need to rm 
          rm -f fract_bonds_running
	else
	  echo "option -keep does not lead to a plot"
	fi
        rm -f tmp1 tmp2 tmp3
       if [ $isdollar1missing != "0" -a $option != "-keep" -a $option != "-keep" ];then
          rm  -f visco$file2display*
        fi
	exit  
      else
       if [ "$option" = "$end_option" ];then
         echo "need a y label"
       else 
         echo "$option is not a valid y label"
       fi
       echo " $1 is not a valid x label"
       echo " valid x labels are  -dens -dgeom : density / geometric density"
       echo "                     -epsx -epsy -epsz : x y and z strain"
       echo ""
       echo " valid y labels are  -elastic_en   : Stored elastic energy"
       echo "                     -crack_length : crack_length"
       exit       
      fi      
    esac
#   a valid y label has been chosen    
    if [ "$plot" != "no" ];then
      let "i+=1"
      if [ "$i" = "1" ];then
# the first y chosen gives the ylabel
        echo "set ylabel $Ylabel" >> plot_$file2display
# the title of the plot is pwd    
        echo "set title  current_dir" >> plot_$file2display
      fi

# with quotes (-Q) one item per line (-1)
# the file to display might be $file2display or visco$file2display
      if [ $isdollar1missing != "0" ];then
        file2plot=$(ls -1 -Q visco$file2display)
      else
        file2plot=$(ls -1 -Q $file2display)
      fi
# calls gnup_lc_lt shell handling variables:
      source $BINARY_std/gnup_lc_lt
    fi
    done
