#!/bin/bash

###########################################################################
# This is a script to display colums of the rupt files in the current 
# directory
###########################################################################

# Christophe.martin@grenoble-inp.fr    November 2006
BINARY_std=$(whereis -b cdp3D | awk '{print $NF}' | rev | sed 's/D3pdc//' | rev)
theuser=`whoami`

file2display=cstatus

lastoption=$(echo "${@: -1}")
isitarange=$(echo $lastoption | grep -c range)
# only one possibility for cstatus
# looking for col 6 to colmax that have none zero columns 
ncols=$(head -1 $file2display | awk '{ print NF}')
ncoly="5"
Option_l=""

while [ "$ncoly" != "$ncols" ]; do
  let "ncoly = ncoly +1"
  nnonzero=$( sed 1d $file2display | awk '{print $'$ncoly'}' | grep -wvc 0)
  if [ "$nnonzero" != "0" ];then 
    Option_l=$Option_l" $ncoly"
  fi
done


# need a $file2display file in the current directory
# need a file2display file in the current directory
if [ -f $file2display ];then     
  echo ""
  numcol=`head -1 $file2display | awk '{print NF }'`
  let "numcol = numcol + 1"
else
  echo '!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!'       
  echo "file $file2display does not exist !"
  echo '!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!'       	 
  exit
fi     
# the list of xaxis columns that are missing in this file:
listxmissing="-dgeom -timestep -time_s -time_h -Temp"
# addmissingXcolumn pastes the column missing into the visco$file2display and returns isdollar1missing 0 or 1
source $BINARY_std/addmissingXcolumn

case $1 in
  -dens )
      Xlabel='"Relative Density "'
      correct_fact=$(grep correct_fact.*=[0-9] input_dp3D | head -1 | cut -c 17-)
      if [ "$correct_fact" = "" ];then
        correct_fact=1.
        Xcolumn='($1)'
      else
        Xcolumn='($1/'$correct_fact')' 
        echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
        echo "Using correction factor from input_dp3D for density  "
        echo "correc_fact="$correct_fact 
        echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
      fi
      ;;
  -dgeom )
      Xlabel='"Geometric Relative Density "'
      Xcolumn='($'$numcol')'
      ;;
  -epsx )
      Xlabel='"Strain (x)"'
      Xcolumn='(-$2)'
      ;; 
  -epsy )
      Xlabel='"Strain (y)"'
      Xcolumn='(-$3)'
      ;; 
  -epsz )
      Xlabel='"Strain (z)"'
      Xcolumn='(-$4)'
      ;; 
  -timestep )
      Xlabel='"Timestep "'
      Xcolumn='($'$numcol')'
      ;;
  -time_s )
      Xlabel='"Time (sec) "'
      Xcolumn='($'$numcol')'
      ;;
  -time_h )
      Xlabel='"Time (hour) "'
      Xcolumn='($'$numcol')'
      ;;
  -Temp )
      Xlabel='"Temperature (deg. C) "'
      Xcolumn='($'$numcol')'
      ;;
     * )
       echo " $1 is not a valid x label"
       echo " valid x labels are  -dens -dgeom : density / geometric density"
       echo "                     -epsx -epsy -epsz : x y and z strain"
       echo ""
       echo " valid y labels are  -status "
       exit 
esac
# gnup_display  is the standard view for gnuplot and display_  
cp -f "$BINARY_std"gnup_display plot_$file2display

    echo "set xlabel $Xlabel" >> plot_$file2display
    if  [ "$isitarange" -ne "0" ];then
      case $lastoption in    
      xrange* )
        range_string=$(echo $lastoption | sed 's/xrange/set xrange /' | sed 's/\//\[/' | sed 's/\//\]/')
        sed -i "s|#set xrange|$range_string|1" plot_$file2display 
      ;;
     yrange* )
        range_string=$(echo $lastoption | sed 's/yrange/set yrange /' | sed 's/\//\[/' | sed 's/\//\]/')
        sed -i "s|#set yrange|$range_string|1" plot_$file2display 
      ;;
      esac
    fi
    let "i=0"
    end_option="$1"0
    for Ycolumn in $Option_l 
    do
      Title=$(awk '{print $'$Ycolumn'}' $file2display | head -1)
      Title=\""${Title:3}"\"
      Ylabel='"Relative contact number"'
      Ycolumn="(\$"$Ycolumn"/\$5)"
      if [ "$plot" != "no" ];then
#   a valid y label has been chosen    
        let "i+=1"
# the first y chosen gives the ylabel      
        if [ "$i" = "1" ];then
          echo "set ylabel $Ylabel" >> plot_$file2display
# the title of the plot is pwd    
          echo "set title  current_dir" >> plot_$file2display
        fi
# with quotes (-Q) one item per line (-1)
# the file to display might be $file2display or visco$file2display
        if [ $nisdollar1missing != "0" ];then
          file2plot=$(ls -1 -Q visco$file2display)
        else
          file2plot=$(ls -1 -Q $file2display)
        fi
# calls gnup_lc_lt shell handling variables:
        source $BINARY_std/gnup_lc_lt
      fi
    done
    gnuplot -geometry 560x400 -persist plot_$file2display 

