#!/bin/bash
! $Id: lastdp3D,v 2.2 2022/09/23 15:20:33 chris Exp $

###########################################################################
# This is a script to get the last 5 (<30 days) dp3D simulations 
###########################################################################

# Christophe.martin@Grenoble-INP.fr    January 2011
theuser=`whoami`
ldir="$1"
hours=`echo "$2" | sed 's/-//g'`

if [ "$ldir" = "" ];then
  echo "lastdp3D usage: lastdp3D directory -hours "
  echo "need a directory"
  echo "by default hours=48"
  exit
fi

# 2 days is the default values (48 hours)
if [ "$hours" = "" ];then
  minutes="2880"
  hours="48"
else
  let "minutes = $hours * 60"
fi


echo "For user $theuser,"
echo "dp3D simulations in the last $hours hours in $ldir:"
ldir=$(realpath $ldir)

find $ldir -type f -mmin -"$minutes" | xargs -r ls -r -t -al | grep -w tstress \
 | awk '{ print $6," ",$7," ",$8," ",$9}'  | sed 's/tstress//' 

exit

list_dir=$(find $ldir -type d -mmin -"$minutes" 2>/dev/null | sed '/test_before_commit/d')
echo "list_dir: $list_dir $minutes"
#list_dir="/home0/chris/compact01/pb_delta"
for dir in $list_dir
  do
    if [ -f $dir/tstress ];then
      ls  -r -t -al $dir | awk '{ print $6," ",$7," ",$8," ",$9}'  | grep -w tstress | sed 's/tstress//'
      echo $dir
      echo ""
    fi
done




exit
# seems faster than:
find ~ -type f -mmin -"$minutes" | xargs -r ls -r -t -al | grep -w tstress  \
 | awk '{ print $6," ",$7," ",$8," ",$9}'  | sed 's/tstress//' 

find /home0/$theuser -type f -mmin -"$minutes" | xargs -r ls -r -t -al | grep -w tstress \
 | awk '{ print $6," ",$7," ",$8," ",$9}'  | sed 's/tstress//' 
