#!/bin/bash
! $Id: lastdp3D,v 1.1 2012/01/23 17:06:21 chris Exp $

###########################################################################
# This is a script to get the last 5 (<30 days) dp3D simulations 
###########################################################################

# Christophe.martin@Grenoble-INP.fr    January 2011
theuser=`whoami`
hours=`echo "$1" | sed 's/-//g'`
# 2 days is the default values (48 hours)
if [ "$hours" = "" ];then
  minutes="2880"
  hours="48"
else
  let "minutes = $hours * 60"
fi
echo "lastdp3D usage: lastdp3D -hours"
echo "by default hours=48"

echo "For user $theuser,"
echo "dp3D simulations in the last $hours hours in /home/$theuser:"

list_dir=$(find /home/$theuser -type d -mmin -"$minutes" 2>/dev/null | sed '/test_before_commit/d')
#list_dir="/home0/chris/compact01/pb_delta"
  for dir in $list_dir
  do
    if [ -f $dir/tstress ];then
      ls  -r -t -al $dir | awk '{ print $6," ",$7," ",$8," ",$9}'  | grep -w tstress | sed 's/tstress//'
      echo $dir
      echo ""
    fi
  done




echo "dp3D simulations in the last $hours hours in /home0/$theuser:"
echo ""
list_dir=$(find /home0/$theuser -type d -mmin -"$minutes" 2>/dev/null | sed '/test_before_commit/d')
#list_dir="/home0/chris/compact01/pb_delta"
  for dir in $list_dir
  do
    if [ -f $dir/tstress ];then
      ls  -r -t -al $dir | awk '{ print $6," ",$7," ",$8," ",$9}'  | grep -w tstress | sed 's/tstress//'
      echo $dir
      echo ""
    fi
  done

exit
# seems faster than:
find ~ -type f -mmin -"$minutes" | xargs -r ls -r -t -al | grep -w tstress  \
 | awk '{ print $6," ",$7," ",$8," ",$9}'  | sed 's/tstress//' 

find /home0/$theuser -type f -mmin -"$minutes" | xargs -r ls -r -t -al | grep -w tstress \
 | awk '{ print $6," ",$7," ",$8," ",$9}'  | sed 's/tstress//' 
